//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustReadIt.WebApp.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JustReadIt.WebApp.Core.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value..
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail address is used by someone else..
        /// </summary>
        internal static string SettingsViewModel_EmailAddressIsAlreadyInUse {
            get {
                return ResourceManager.GetString("SettingsViewModel_EmailAddressIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is invalid..
        /// </summary>
        internal static string SettingsViewModel_EmailAddressIsInvalid {
            get {
                return ResourceManager.GetString("SettingsViewModel_EmailAddressIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is too long..
        /// </summary>
        internal static string SettingsViewModel_EmailAddressIsTooLong {
            get {
                return ResourceManager.GetString("SettingsViewModel_EmailAddressIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address required..
        /// </summary>
        internal static string SignInViewModel_EmailAddressIsRequired {
            get {
                return ResourceManager.GetString("SignInViewModel_EmailAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address too long..
        /// </summary>
        internal static string SignInViewModel_EmailAddresssTooLong {
            get {
                return ResourceManager.GetString("SignInViewModel_EmailAddresssTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string SignInViewModel_PasswordIsRequired {
            get {
                return ResourceManager.GetString("SignInViewModel_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long..
        /// </summary>
        internal static string SignInViewModel_PasswordIsTooLong {
            get {
                return ResourceManager.GetString("SignInViewModel_PasswordIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is required..
        /// </summary>
        internal static string SignUpViewModel_EmailAddressIsRequired {
            get {
                return ResourceManager.GetString("SignUpViewModel_EmailAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is too long..
        /// </summary>
        internal static string SignUpViewModel_EmailAddressIsTooLong {
            get {
                return ResourceManager.GetString("SignUpViewModel_EmailAddressIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and password confirmation are different..
        /// </summary>
        internal static string SignUpViewModel_PasswordAndPasswordConfirmationAreDifferent {
            get {
                return ResourceManager.GetString("SignUpViewModel_PasswordAndPasswordConfirmationAreDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is required..
        /// </summary>
        internal static string SignUpViewModel_PasswordConfirmationIsRequired {
            get {
                return ResourceManager.GetString("SignUpViewModel_PasswordConfirmationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is too long..
        /// </summary>
        internal static string SignUpViewModel_PasswordConfirmationIsTooLong {
            get {
                return ResourceManager.GetString("SignUpViewModel_PasswordConfirmationIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string SignUpViewModel_PasswordIsRequired {
            get {
                return ResourceManager.GetString("SignUpViewModel_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long..
        /// </summary>
        internal static string SignUpViewModel_PasswordIsTooLong {
            get {
                return ResourceManager.GetString("SignUpViewModel_PasswordIsTooLong", resourceCulture);
            }
        }
    }
}
